### ISSUE TITLE
Hi/Lo Temp decimals

### ISSUE THREAD

**Issue by ik0adr** [Qrome/marquee-scroller#217]
Hi and thanks for the nice work.
Would it be possible to have Hi/Lo Temps shown as integers, without decimals?
I see this cyted in some pull request, but in current 2.18 they are shown as XX.XX...
Many thanks again,

Federico from Rome, Italy

**Comment by Qrome** [comment]
There have been no pull request on the official code line for this.   Though this is a very simple change.

Edit the OpenWeatherMapClient.cpp file and on line 259 and on 264 rap the returned value with rouncValue().

Example, change the following line 259:

return weathers[index].high;

to

return roundValue(weathers[index].high);

Do the same thing for line 264.   

I will include this on the 2.19 -- just so people understand, the high/low, it is the current high and low values of the current weather from several stations in the region.

**Comment by ik0adr** [comment]
Ok, thanks for the quick reply and info.
I will wait for 2.19, I uploaded the bin file, much easier 😜

Inviato da iPhone

**Comment by davsav** [comment]
@ik0adr I too was bothered by the two decimal place temperature conversion and had previously edited and recompiled the code to fix that.  

Since the code had to be updated to fix the time issue and I had to do the fix again, I did a fork and my compiled binary is available at 

[https://github.com/davsav/marquee-scroller/blob/davsav-patch-round-temp/marquee.ino.d1_mini_2.18a.bin](url)

You can do an over the air update to what I called 2.18a.  Note: I did not compile a wide version, just the narrow since that is what I'm using.

I did a pull request, my first, so forgive me if I screwed it up, which it appears I did as the edited CPP files are not in the files directory.

**Comment by ik0adr** [comment]
Sorry, link doesn't work..

Il giorno ven 12 nov 2021 alle ore 18:28 davsav ***@***.***>
ha scritto:

**Comment by ik0adr** [comment]
Don't mind, it worked like a charm, thanks a lot

**Comment by davsav** [comment]
Sorry, my bad.  I fixed it in my post above but here it is again:

[https://github.com/davsav/marquee-scroller/blob/davsav-patch-round-temp/marquee.ino.d1_mini_2.18a.bin](https://github.com/davsav/marquee-scroller/blob/davsav-patch-round-temp/marquee.ino.d1_mini_2.18a.bin)

At that page, click the download button on the right side about half way down.

**Comment by ik0adr** [comment]
Thanks!!!
