### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rapmann02** [Qrome/marquee-scroller#45]
error: espcomm_upload_mem failed

**Comment by Qrome** [comment]
Please provide as much information as you can.
Arduino Version
Board Version
Board Selected

I am sure your issue is NOT related to the software.  Sounds like you are asking for help just getting the IDE to work with your ESP8266 -- have you tested using the ESP8266 -> Blink program?   If you can't get that to work, then perhaps there is something wrong with the board you have.

**Comment by rapmann02** [comment]
Hello again. 
One Man in the Video (Mert Arduino) does not have to select a news source. But I have to select one. Because I would like to have Swiss News or German. He putted the API Key in and it worked for him. I also put my in but I have to select a US News source. I want German or Swiss News please. What can I do?

Raphael Achermann

**Comment by rapmann02** [comment]
Can I put in the API Key in „Settings.h“ and delete „reuters“ as standard news source?

Raphael Achermann
