### ISSUE TITLE
Slip advice empty

### ISSUE THREAD

**Issue by satbeppo** [Qrome/marquee-scroller#63]
Hi, the Slip advice displays nothing for about two weeks.
The server "api.adviceslip.com" is working 
Thanks a lot for work. I like that scroller

**Comment by MrJabu** [comment]
i have the same issue

**Comment by Qrome** [comment]
The issue is adviceslip.com recently changed over to HTTPS only.   The code use refrencing the http and will not follow the 301 redirect response over to the HTTPS version of the API.   I have been attempting to change the service over to use HTTPS however it is hitting memory restraints when trying to make the SSL call that is required.  Apparently it takes a lot of memory to make a SSL call and we are hitting the limits of the Wemos D1 Mini.   It might require some major changes in the marquee code base to try and free up the memory required.

**Comment by Qrome** [comment]
I have decided to remove Advice Slip from the project for now.   Since adding the HTTPS request is now required, it pushes up into the memory constraints of the standard Wemos D1 Mini.   We may add this back if we can optimize the code a bit more.
Thanks.   Version 2.6 has it removed.
